# Site settings
title: alexmgrant
email: alexmgrant@me.com
description: > # this means to ignore newlines until "baseurl:"
  A developer with a passion for learning, tinkering, breaking and then fixing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexgrant.xyz" # the base hostname & protocol for your site
twitter_username: lubybear
github_username:  alexmgrant

#seo
author:
  alexmgrant
url:
  alexmgrant.github.io

# Build settings
markdown: kramdown

gems: [
  'jekyll-github-metadata',
  'jekyll-seo-tag'
]
